@host = http://localhost:8080
@baseUrl = {{host}}/api/v1
@contentType = application/json

###
GET {{host}}
Content-Type: {{contentType}}

###
GET {{host}}/healthcheck
Content-Type: {{contentType}}

###
POST {{baseUrl}}/pins
Content-Type: {{contentType}}

{
  "title": "Biblioteca Municipal",
  "description": "Entrada com elevador e piso tátil",
  "category": "Nao Acessivel",
  "latitude": -23.5025,
  "longitude": -47.4531
}

###
POST {{baseUrl}}/pins
Content-Type: {{contentType}}

{
  "title": "Restaurante Popular",
  "description": "Banheiro adaptado e acesso para cadeirantes",
  "category": "Acessivel",
  "latitude": -23.5038,
  "longitude": -47.4542
}

###
POST {{baseUrl}}/pins
Content-Type: {{contentType}}

{
  "title": "Estação de Ônibus",
  "description": "Plataforma com rampas e sinalização em braile",
  "category": "Parcialmente Acessivel",
  "latitude": -23.5049,
  "longitude": -47.4553
}

###
GET {{baseUrl}}/pins
Content-Type: {{contentType}}

###
GET {{baseUrl}}/pins/22
Content-Type: {{contentType}}

###
PATCH {{baseUrl}}/pins/21
Content-Type: {{contentType}}

{
  "title": "Meu Pin Editado",
  "description": "Descrição do pin editada",
  "category": "Categoria Editada",
  "longitude": -46.6340,
  "latitude": -23.5510
}

###
DELETE {{baseUrl}}/pins/21
Content-Type: {{contentType}}