name: backend-upx4
services:
  # backend:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     DATABASE_URL: postgres://postgres:1234@postgres:5432/upx4_db
  #   depends_on:
  #     - postgres
  postgres:
    image: postgis/postgis:16-3.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: upx4_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5430:5432"

volumes:
  pgdata: